version: "3.3"
services:
  dsa:
    image: abrakadabra21099/dsa-alpine:0.2
    build: .
#    ports:
#      - "137-139:137-139"
#      - "445:445"
    volumes:
      - /srv/cron/data/:/etc/cron.d
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
